# Generated by Django 6.0.2 on 2026-02-13 14:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Colonies',
            },
        ),
        migrations.CreateModel(
            name='LandlordInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField(db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('colony_name', models.CharField(db_index=True, max_length=100)),
                ('room_type', models.CharField(choices=[('1_RK', '1 Room Set'), ('2_RK', '2 Room Set'), ('1_BHK', '1 BHK'), ('2_BHK', '2 BHK')], db_index=True, default='1_RK', max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='room_videos/')),
                ('google_map_link', models.URLField(blank=True, help_text='Google Maps link here', null=True)),
                ('total_inventory', models.IntegerField(default=1, help_text='How many sets of this room are available?')),
                ('broker_name', models.CharField(default='Office', help_text='Name of the Broker', max_length=100)),
                ('broker_phone', models.CharField(blank=True, default='', help_text='PPhone number of Broker (Leave empty if none)', max_length=15)),
                ('landlord_name', models.CharField(blank=True, help_text='Name of the Landlord', max_length=100, null=True)),
                ('landlord_phone', models.CharField(blank=True, help_text='Phone number of the Landlord', max_length=20, null=True)),
                ('tenant_type', models.CharField(choices=[('BOYS', 'Boys Only'), ('GIRLS', 'Girls Only'), ('FAMILY', 'Family Only'), ('ANY', 'Anyone (Boys/Girls/Family)')], db_index=True, default='ANY', help_text='Who is this room for?', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.room')),
            ],
        ),
        migrations.CreateModel(
            name='TenantInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
        ),
    ]
