# Generated by Django 6.0.2 on 2026-02-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='broker_phone',
            field=models.CharField(blank=True, default='', help_text='Phone number of Broker (Leave empty if none)', max_length=15),
        ),
        migrations.AlterField(
            model_name='room',
            name='landlord_phone',
            field=models.CharField(blank=True, help_text='Phone number of the Landlord', null=True),
        ),
    ]
