# Generated by Django 6.0.1 on 2026-02-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_room_image_room_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='landlord_name',
            field=models.CharField(default='Office', help_text='Name of the Landlord or Broker', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='landlord_phone',
            field=models.CharField(default='', help_text='Phone number of the Landlord/Broker', max_length=15),
        ),
    ]
