# Generated by Django 6.0.2 on 2026-02-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_broker_phone_alter_room_landlord_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='place_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
