# Generated by Django 6.0.1 on 2026-02-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_landlord_name_room_landlord_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='tenant_type',
            field=models.CharField(choices=[('BOYS', 'Boys Only'), ('GIRLS', 'Girls Only'), ('FAMILY', 'Family Only'), ('ANY', 'Anyone (Boys/Girls/Family)')], default='ANY', help_text='Who is this room for?', max_length=10),
        ),
    ]
