# Generated by Django 6.0.2 on 2026-02-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_distance_km_room_place_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='place_name',
            field=models.CharField(blank=True, help_text='places like School, college, or any work place', max_length=150, null=True),
        ),
    ]
