# Generated by Django 6.0.1 on 2026-02-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_room_tenant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantinquiry',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
