# Generated by Django 6.0.2 on 2026-02-04 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tenantinquiry_payment_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Colonies',
            },
        ),
        migrations.RenameField(
            model_name='landlordinquiry',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tenantinquiry',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='landlordinquiry',
            name='is_contacted',
        ),
        migrations.RemoveField(
            model_name='tenantinquiry',
            name='is_contacted',
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(default='1_RK', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='room_videos/'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(upload_to='room_images/'),
        ),
        migrations.AlterField(
            model_name='tenantinquiry',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room'),
        ),
    ]
