# Generated by Django 6.0.2 on 2026-02-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_colony_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='colony_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(db_index=True, default='1_RK', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='tenant_type',
            field=models.CharField(choices=[('BOYS', 'Boys Only'), ('GIRLS', 'Girls Only'), ('FAMILY', 'Family Only'), ('ANY', 'Anyone (Boys/Girls/Family)')], db_index=True, default='ANY', help_text='Who is this room for?', max_length=10),
        ),
    ]
