# Generated by Django 6.0.2 on 2026-02-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_room_colony_name_alter_room_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='broker_name',
            field=models.CharField(default='Office', help_text='Name of the Broker', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='broker_phone',
            field=models.CharField(default='', help_text='Phone number of Broker', max_length=15),
        ),
        migrations.AlterField(
            model_name='room',
            name='landlord_name',
            field=models.CharField(blank=True, help_text='Name of the Landlord', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='landlord_phone',
            field=models.CharField(blank=True, help_text='Phone number of the Landlord', max_length=20, null=True),
        ),
    ]
