# Generated by Django 6.0.2 on 2026-02-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_room_broker_name_room_broker_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='google_map_link',
            field=models.URLField(blank=True, help_text='Google Maps link here', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='total_inventory',
            field=models.IntegerField(default=1, help_text='How many sets of this room are available?'),
        ),
    ]
