# Generated by Django 6.0.2 on 2026-02-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_room_google_map_link_room_total_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('1_RK', '1 Room Set'), ('2_RK', '2 Room Set'), ('1_BHK', '1 BHK'), ('2_BHK', '2 BHK')], db_index=True, default='1_RK', max_length=50),
        ),
    ]
