# Generated by Django 6.0.2 on 2026-02-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='broker_phone',
            field=models.CharField(blank=True, default='', help_text='PPhone number of Broker (Leave empty if none)', max_length=15),
        ),
    ]
