# Generated by Django 6.0.2 on 2026-02-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_room_broker_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantinquiry',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
