# Generated by Django 6.0.2 on 2026-02-13 12:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_tenantinquiry_is_connected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colony',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
